import pandas as pd
import matplotlib.pyplot as plt
df = pd.read_csv("data.csv")
print(" FIRST 5 ROWS ")
print(df.head())
print("\n DATA INFO ")
print(df.info())
print("\n STATISTICS ")
print(df.describe())
print("\nMISSING VALUES")
print(df.isnull().sum())
plt.figure()
df.groupby("City")["Salary"].mean().plot(kind='bar')
plt.title("Average Salary by City")
plt.ylabel("Salary")
plt.xlabel("City")
plt.savefig("bar_chart.png")
plt.show()
plt.figure()
df["Salary"].plot(kind='hist', bins=5)
plt.title("Salary Distribution")
plt.xlabel("Salary")
plt.savefig("histogram.png")
plt.show()

